
####################################
#机器人配置
####################################
# 是否启用调试模式，输出原始 JSON 消息
debug: false

# WebSocket 地址
WebSocket: "ws://127.0.0.1:8080"

# 是否自动连接
AutoOpen: true

# 断开是否自动重连
Reconnect: true

# 最多重连次数
MaxReconnect: 10

# 每个任务最大处理时间（秒）
TaskTimeout: 10

# 最大线程池数量（未实现线程池时用于保留）
MaxActiveCount: 10

#跨服标识
server-name: server

##########################################
#白名单配置
##########################################

#是否启用白名单
whitelist-enable: true

#默认密码，可到 https://www.lddgo.net/string/randompassword 生成
default-password: yC[c=a8G

#登录提示词
login-prompt: "登录"

#Authme注册提示词
register-prompt: "§b📢 §f请输入您的§cQQ号码 §f或 输入§c/register <密码> 密码 §f完成注册"

#输入完毕后的验证码提示词
title-code: "验证码 §a{0}"
subtitle-code: "🔈§f请在群内 §c@机器人 §a<验证码> §f完成发送"
login-mssage: "🔈§f请在群内发送 §b@机器人 §c登录 或 §f输入§c/login <密码> §f完成登录"
login-success: "您已成功登录服务器，祝您游戏愉快！"

#######################
#群服互联
#######################

#是否开启群服互联
chatreply-enable: true

#群服互联触发提示词
startsWith: "say"

#无白名单人员昵称
entries-Empty: "群成员"
#服务器内的消息格式
chat-format: "🐧§cQQ群 §7| §f"

#是否启用敏感词处理
Enable: true
Cloud-Thesaurus:
  Enabled: true
  Ignored: ['nt']   # 云词库忽略的词（不当敏感词处理）
  Urls:
    - 'https://raw.githubusercontent.com/Yurinann/Filter-Thesaurus-Cloud/main/database.json'
    # - 'https://raw.githubusercontent.com/konsheng/Sensitive-lexicon/main/ThirdPartyCompatibleFormats/TrChat/SensitiveLexicon.json'
Local:
  - NMSL
  - fuck
  - shit
Ignored-Punctuations: ['!','.',',','#','$','%','&','*','(',')','|','?','/','@','"','\\',';','[',']','{','}','+','~','-','_','=','^','<','>',' ','　','！','。','，','￥','（','）','？','、','“','‘','；','【','】','——','……','《','》','\\', '`']

Replacement: '*'



######################
#Deepseek API 相关
######################
deepseek-enable: true
deepseek-api-key: "填入你的deepseek key密匙"
ignored-prefix:
  - "^\\."       # 忽略以 . 开头的消息
  - "^/"         # 忽略命令消息
  - "^登录\\s*"   # 忽略以“登录”开头的消息（允许空格）
  - "^list\\b"    # 忽略以 list 开头的单词
  - "^say\\b"     # 忽略以 say 开头的单词
  - "^\\d{4}\\s*" # 忽略以4位数字开头的消息

#AI人格设定
personality: "温柔、体贴、爱说简单话的女朋友，总是安静地倾听，温柔地回应，回复不超过100字"
